apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    name: web
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
      targetPort: 3000
  externalIPs:
    - 78.47.159.67
  selector:
    name: web
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
        - image: localhost:5000/web:8
          name: web
          env:
            - name: NODE_ENV
              value: development
            - name: AWS_REGION
              value: eu-central-1
          ports:
            - containerPort: 3000
#---
#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: balancer
#  annotations:
#    kubernetes.io/ingress.class: "nginx"
#spec:
#  rules:
#  - host: cloud.modxvm.com
#    http:
#      paths:
#      - path: /
#        backend:
#          serviceName: web
#          servicePort: 80
